---
- hosts: archivers
  tasks:
    - name: Creates directory
      file: path=/home/ubuntu state=directory

    - name: Check daily backup
      command: /vagrant/automated_checks.py --backup daily
      register: daily_reg
    - set_fact: daily="{{ daily_reg.stdout | from_json }}"
    - local_action: 
        copy content={{ daily | to_nice_json }} dest=/home/ubuntu/daily.json
    - copy:
        src: /home/ubuntu/daily.json
        dest: /home/ubuntu/
        owner: ubuntu
        mode: 0755
    - debug: var=daily
      when: daily.codes.result == 1 or daily.databases.result == 1

    - stat: 
        path: /home/ubuntu/daily.json
      register: daily_file
    - debug: var=daily_file

    - name: Check weekly backup
      command: /vagrant/automated_checks.py --backup weekly
      register: weekly_reg
    - set_fact: weekly="{{ weekly_reg.stdout | from_json }}"
    - local_action: 
        copy content={{ weekly | to_nice_json }} dest=/home/ubuntu/weekly.json
    - copy:
        src: /home/ubuntu/weekly.json
        dest: /home/ubuntu/
        owner: ubuntu
        mode: 0755
    - debug: var=weekly
      when: weekly.codes.result == 1 or weekly.databases.result == 1
    
    - stat: 
        path: /home/ubuntu/weekly.json
      register: weekly_file
    - debug: var=weekly_file

    - name: Check monthly backup
      command: /vagrant/automated_checks.py --backup monthly
      register: monthly_reg
    - set_fact: monthly="{{ monthly_reg.stdout | from_json }}"
    - local_action: 
        copy content={{ monthly | to_nice_json }} dest=/home/ubuntu/monthly.json
    - copy:
        src: /home/ubuntu/monthly.json
        dest: /home/ubuntu/
        owner: ubuntu
        mode: 0755
    - debug: var=monthly
      when: monthly.all.result == 1

    - stat: 
        path: /home/ubuntu/monthly.json
      register: monthly_file
    - debug: var=monthly_file

    - name: Check yearly backup
      command: /vagrant/automated_checks.py --backup yearly
      register: yearly_reg
    - set_fact: yearly="{{ yearly_reg.stdout | from_json }}"
    - local_action: 
        copy content={{ yearly | to_nice_json }} dest=/home/ubuntu/yearly.json
    - copy:
        src: /home/ubuntu/yearly.json
        dest: /home/ubuntu/
        owner: ubuntu
        mode: 0755
    - debug: var=yearly
      when: yearly.all.result == 1

    - stat: 
        path: /home/ubuntu/yearly.json
      register: yearly_file
    - debug: var=yearly_file

    - mail:
        host: smtp.gmail.com
        port: 587
        username: "{{ lookup('env', 'GOOGLE_MAIL_APP_USER') }}"
        password: "{{ lookup('env', 'GOOGLE_MAIL_APP_PASS') }}"
        to: "{{ lookup('env', 'GOOGLE_MAIL_SEND_TO') }}"
        subject: Missing daily files for - {{ ansible_hostname }}
        body: 'Missing daily files for - {{ ansible_hostname }}'
        attach: /home/ubuntu/daily.json
      delegate_to: localhost
      when: daily_file.stat.exists is defined and daily_file.stat.exists

    - mail:
        host: smtp.gmail.com
        port: 587
        username: "{{ lookup('env', 'GOOGLE_MAIL_APP_USER') }}"
        password: "{{ lookup('env', 'GOOGLE_MAIL_APP_PASS') }}"
        to: "{{ lookup('env', 'GOOGLE_MAIL_SEND_TO') }}"
        subject: Missing weekly files for - {{ ansible_hostname }}
        body: 'Missing weekly files for - {{ ansible_hostname }}'
        attach: /home/ubuntu/weekly.json
      delegate_to: localhost
      when: weekly_file.stat.exists is defined and weekly_file.stat.exists

    - mail:
        host: smtp.gmail.com
        port: 587
        username: "{{ lookup('env', 'GOOGLE_MAIL_APP_USER') }}"
        password: "{{ lookup('env', 'GOOGLE_MAIL_APP_PASS') }}"
        to: "{{ lookup('env', 'GOOGLE_MAIL_SEND_TO') }}"
        subject: Missing monthly files for - {{ ansible_hostname }}
        body: 'Missing monthly files for - {{ ansible_hostname }}'
        attach: /home/ubuntu/monthly.json
      delegate_to: localhost
      when: monthly_file.stat.exists is defined and monthly_file.stat.exists

    - mail:
        host: smtp.gmail.com
        port: 587
        username: "{{ lookup('env', 'GOOGLE_MAIL_APP_USER') }}"
        password: "{{ lookup('env', 'GOOGLE_MAIL_APP_PASS') }}"
        to: "{{ lookup('env', 'GOOGLE_MAIL_SEND_TO') }}"
        subject: Missing yearly files for - {{ ansible_hostname }}
        body: 'Missing yearly files for - {{ ansible_hostname }}'
        attach: /home/ubuntu/yearly.json
      delegate_to: localhost
      when: yearly_file.stat.exists is defined and yearly_file.stat.exists

    - name: Colelct all JSON files
      find:
        paths: /home/ubuntu
        patterns: "*.json"
      register: files_to_delete

    - name: Remove all JSON files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_to_delete.files }}"

    - name: Colelct All local JSON files
      find:
        paths: /home/ubuntu
        patterns: "*.json"
      register: files_to_delete2
      delegate_to: localhost

    - name: Remove all local JSON files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_to_delete2.files }}"
      delegate_to: localhost

